apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aki-detection-state
  namespace: peace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aki-detection
  namespace: peace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aki-detection
  template:
    metadata:
      labels:
        app: aki-detection
    spec:
      containers:
      - name: aki-detection
        image: imperialswemlsspring2024.azurecr.io/coursework4-peace:v1-amd64
        command: ["/bin/sh", "-c"]
        args:
          - >
            ./main.py
            --history=/hospital-history/history.csv
            --mllp=$MLLP_ADDRESS
            --pager=$PAGER_ADDRESS
        env:
        - name: MLLP_ADDRESS
          value: peace-simulator.hospital:8440
        - name: PAGER_ADDRESS
          value: peace-simulator.hospital:8441
        volumeMounts:
          - mountPath: "/hospital-history"
            name: hospital-history
            readOnly: true
        resources:
          requests:
            memory: 1Gi
            cpu: 1
      initContainers:
      - name: copy-hospital-history
        image: imperialswemlsspring2024.azurecr.io/coursework4-history
        volumeMounts:
          - mountPath: "/hospital-history"
            name: hospital-history
          - mountPath: "/state"
            name: aki-detection-state
        resources:
          requests:
            memory: 1Gi
            cpu: 1
      volumes:
      - name: hospital-history
        emptyDir:
          sizeLimit: 50Mi
      - name: aki-detection-state
        persistentVolumeClaim:
          claimName: aki-detection-state